// <auto-generated />
using System;
using ERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.EntityModels.Migrations
{
    [DbContext(typeof(AMSContext))]
    [Migration("20250723065907_AddNewModels")]
    partial class AddNewModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Models.AMS.t_level", b =>
                {
                    b.Property<int>("f_permissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_permissionID"));

                    b.Property<int>("f_levelAmount")
                        .HasColumnType("int");

                    b.Property<int>("f_permissionLevel")
                        .HasColumnType("int");

                    b.HasKey("f_permissionID");

                    b.ToTable("t_level");
                });

            modelBuilder.Entity("ERP.Models.AMS.t_permission", b =>
                {
                    b.Property<int>("f_roleId")
                        .HasColumnType("int");

                    b.Property<int>("f_pageId")
                        .HasColumnType("int")
                        .HasColumnName("f_pageId");

                    b.Property<bool>("f_type")
                        .HasColumnType("bit");

                    b.HasKey("f_roleId", "f_pageId");

                    b.ToTable("t_permission", (string)null);
                });

            modelBuilder.Entity("ERP.Models.AMS.t_role", b =>
                {
                    b.Property<int>("f_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_id"));

                    b.Property<int?>("f_approvalLevel")
                        .HasColumnType("int");

                    b.Property<int?>("f_permissionLevel")
                        .HasColumnType("int");

                    b.Property<int?>("f_procurementLevel")
                        .HasColumnType("int");

                    b.Property<int?>("f_quotationLevel")
                        .HasColumnType("int");

                    b.Property<string>("f_roleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("f_sessionTime")
                        .HasColumnType("int");

                    b.HasKey("f_id");

                    b.ToTable("t_role");
                });

            modelBuilder.Entity("ERP.Models.AMS.t_user", b =>
                {
                    b.Property<int>("f_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_id"));

                    b.Property<string>("f_account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("f_createDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("f_isLock")
                        .HasColumnType("bit");

                    b.Property<string>("f_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_pwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("f_role")
                        .HasColumnType("int");

                    b.Property<string>("f_sessionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("f_id");

                    b.ToTable("t_user");
                });
#pragma warning restore 612, 618
        }
    }
}
