CREATE TABLE [dbo].[t_1000Staff] (
    [StaffId]                       INT             IDENTITY (1, 1) NOT NULL,
    [StaffUid]                      NVARCHAR (MAX)  NULL,
    [ChineseName]                   NVARCHAR (32)   NOT NULL,
    [EnglishName]                   NVARCHAR (32)   NULL,
    [Gender]                        INT             NOT NULL,
    [Account]                       NVARCHAR (32)   NOT NULL,
    [ContactPhone]                  NVARCHAR (32)   NOT NULL,
    [BankAccount]                   NVARCHAR (32)   NOT NULL,
    [ContactAddress]                NVARCHAR (64)   NOT NULL,
    [Email]                         NVARCHAR (64)   NOT NULL,
    [OfficialEmail]                 NVARCHAR (64)   NULL,
    [Birthday]                      DATETIME2 (7)   NOT NULL,
    [HighestEducation]              NVARCHAR (32)   NOT NULL,
    [OnBoardDate]                   DATETIME2 (7)   NOT NULL,
    [ResignationDate]               DATETIME2 (7)   NULL,
    [IdCard]                        NVARCHAR (16)   NOT NULL,
    [LaborPension]                  DECIMAL (12, 2) NOT NULL,
    [EmergencyContact1Name]         NVARCHAR (32)   NULL,
    [EmergencyContact1Relationship] NVARCHAR (16)   NULL,
    [EmergencyContact1Phone]        NVARCHAR (32)   NULL,
    [EmergencyContact1Address]      NVARCHAR (64)   NULL,
    [EmergencyContact2Name]         NVARCHAR (32)   NULL,
    [EmergencyContact2Relationship] NVARCHAR (16)   NULL,
    [EmergencyContact2Phone]        NVARCHAR (32)   NULL,
    [EmergencyContact2Address]      NVARCHAR (64)   NULL,
    [LineId]                        NVARCHAR (64)   NULL,
    [ExtensionNumber]               INT             NULL,
    [BusinessPhone]                 NVARCHAR (32)   NULL,
    [Headshot]                      VARBINARY (MAX) NULL,
    [BankName]                      NVARCHAR (64)   NULL,
    [SubBankName]                   NVARCHAR (32)   NULL,
    [BloodType]                     INT             NOT NULL,
    CONSTRAINT [PK_t_1000Staff] PRIMARY KEY CLUSTERED ([StaffId] ASC)
);

